//! Hand-labelled paths, written by hand before the generator and kept apart from it. Made
//! up; no real user's files. Names used here are held out of training (`synth::held_out`).

use crate::model::Category::{self, *};

/// (path, is_file, category)
pub const PATHS: &[(&str, bool, Category)] = &[
    ("~/Library/Caches/com.spotify.client", false, Caches),
    ("~/Library/Caches/Google/Chrome", false, Caches),
    ("~/Library/Caches/Homebrew/downloads", false, Caches),
    ("~/Library/Caches/pip", false, Caches),
    ("~/Library/Caches/ms-playwright", false, Caches),
    ("~/Library/Developer/Xcode/DerivedData/Runner-abcdefghijklmnopqrstuvwxyzab", false, Developer),
    ("~/Library/Developer/Xcode/iOS DeviceSupport/17.4 (21E219)", false, Developer),
    ("~/code/website/node_modules", false, Developer),
    ("~/code/petal/target", false, Developer),
    ("~/code/ml-experiments/.venv", false, Developer),
    ("~/code/app/ios/Pods", false, Developer),
    ("~/code/dashboard/.next", false, Developer),
    ("~/code/android-app/build", false, Developer),
    ("~/code/android-app/.gradle", false, Developer),
    ("~/.npm/_cacache", false, Developer),
    ("~/.cargo/registry/cache", false, Developer),
    ("~/.gradle/caches", false, Developer),
    ("~/.cache/huggingface/hub", false, Developer),
    ("~/Library/Caches/com.apple.Safari", false, Caches),
    ("~/.Trash", false, Downloads),
    ("~/code/scratch/__pycache__", false, Developer),
    ("~/Library/Application Support/Code/CachedData", false, Caches),
    ("~/Library/Application Support/Slack/Cache", false, Caches),
    ("/private/var/folders/x1/abc123/X/com.google.Chrome.code_sign_clone", false, Caches),
    ("~/Downloads", false, Downloads),
    ("~/Downloads/Xcode_15.4.xip", true, Downloads),
    ("~/Downloads/ubuntu-24.04-desktop-arm64.iso", true, Downloads),
    ("~/Downloads/Zoom.pkg", true, Downloads),
    ("~/Library/Developer/Xcode/Archives/2024-03-11", false, Developer),
    ("~/Library/Developer/CoreSimulator/Devices", false, Developer),
    ("~/Library/Application Support/MobileSync/Backup/00008110-001A2B3C", false, AppData),
    ("~/Library/Containers/com.docker.docker/Data/vms/0/data/Docker.raw", true, Developer),
    ("~/Movies/Final Cut Projects/Render Files", false, Media),
    ("~/Library/Application Support/Steam/steamapps/common/Baldurs Gate 3", false, Apps),
    ("~/.ollama/models", false, Developer),
    ("~/Library/Group Containers/group.com.apple.coreservices.useractivityd/shared-pasteboard", false, AppData),
    ("~/Library/Application Support/Google/Chrome/Default/Service Worker/CacheStorage", false, Caches),
    ("~/Library/Mail/V10/MailData", false, AppData),
    ("~/Library/Mail/V10/4A1B2C3D/INBOX.mbox", false, AppData),
    ("~/Library/Logs/DiagnosticReports", false, Caches),
    ("~/Pictures/Photos Library.photoslibrary", false, Media),
    ("~/Documents/Taxes/2023", false, Documents),
    ("~/Documents/thesis-final.docx", true, Documents),
    ("~/Music/Logic/Album Sessions", false, Media),
    ("~/Movies/Wedding 2022 RAW", false, Media),
    ("~/code/petal/.git", false, Developer),
    ("~/code/petal/src", false, Developer),
    ("~/Library/Application Support/1Password", false, AppData),
    ("~/Library/Messages/Attachments", false, AppData),
    ("~/Library/Messages/chat.db", true, AppData),
    ("~/Library/Keychains", false, AppData),
    ("~/Library/Mobile Documents/com~apple~CloudDocs", false, Documents),
    ("~/Library/Application Support/Obsidian", false, AppData),
    ("~/Parallels/Windows 11.pvm", false, AppData),
    ("~/Library/Containers/com.apple.Notes", false, AppData),
    ("~/Library/Application Support/AddressBook", false, AppData),
    ("~/Desktop/Screenshots", false, Media),
    ("~/Library/Preferences", false, AppData),
    ("/Applications/Xcode.app", false, Apps),
    ("~/Library/Application Support/Claude/vm_bundles", false, AppData),
    // Kinds the first set hardly covered.
    ("/System/Volumes/Data", false, Mixed),
    ("/Users/alex", false, Mixed),
    ("/Users/alex/Library", false, Mixed),
    ("/System/Volumes/Data/Users", false, Mixed),
    ("/Users/Shared", false, Mixed),
    ("/Volumes/Backup Disk", false, Mixed),
    ("/System/Volumes/Data/Applications", false, Apps),
    ("/Applications/Utilities", false, Apps),
    ("/Applications/Microsoft Excel.app", false, Apps),
    ("/System/Volumes/Data/Library/Application Support", false, System),
    ("/System/Volumes/Data/private/var/db", false, System),
    ("/Library/Frameworks", false, System),
    ("/private/var/vm", false, System),
    ("/Library/Audio/Apple Loops", false, Media),
    ("/opt/homebrew", false, Developer),
    ("~/Library/Developer", false, Developer),
    ("~/Documents/GitHub/infra", false, Developer),
    ("~/Pictures/Lightroom Catalog", false, Media),
    ("~/Pictures/Photo Booth Library", false, Media),
    ("~/Music/iTunes/iTunes Media", false, Media),
    ("~/Movies/TV/Media", false, Media),
    ("~/Pictures/Photos Library.photoslibrary/originals", false, Media),
    ("~/Desktop/Invoices", false, Documents),
    ("~/Downloads/IMG_4021.MOV", true, Downloads),
    ("~/Downloads/archive", false, Downloads),
    ("~/.Trash/old-project", false, Downloads),
    ("~/Library/Caches/com.apple.akd", false, Caches),
    ("~/Library/Containers/com.apple.photoanalysisd", false, AppData),
    ("~/Library/Mail", false, AppData),
];
